runtime: python39
entrypoint: gunicorn -b :$PORT app:app

instance_class: F2
automatic_scaling:
  min_instances: 0
  max_instances: 1

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always
